swagger: "2.0"
info:
  version: "0.0.1"
  title: Sprint App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: "/"
# 
schemes:
  # tip: remove http to make production-grade
  - http
paths:
  /pastSprints:
    post:
      tags:
      - "pastSprints"
      summary: "Add a sprint to the database"
      description: ""
      operationId: "pastSprints"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "name"
        
  